### ISSUE TITLE
Skipping python-3.8, NVCV python bindings not installed[BUG]

### ISSUE THREAD

**Issue by bzha5848** [CVCUDA/CV-CUDA#101]
Hello there,

I'm having an issue when running ./run_tests.sh:
![image](https://github.com/CVCUDA/CV-CUDA/assets/49177682/9a02766a-760d-4e4b-997b-8774bce828aa)

I follow these tute to setup the environment
https://blog.csdn.net/u012863603/article/details/128647822
https://cvcuda.github.io/installation.html

And My nvcv version is 0.2.1_alpha

Does anyone meet this error before?

Thanks so much!!

**Comment by DAVID-Hown** [comment]
@bzha5848 hi, Did you solve it?

**Comment by bhaefnerNV** [comment]
Hi,
We will close this issue for now, due to inactivity - please feel free to reopen if the problem persists.
