### ISSUE TITLE
ModuleNotFoundError: No module named 'cvcuda'

### ISSUE THREAD

**Issue by yang0907** [CVCUDA/CV-CUDA#11]
**What is your question?**
使用源码的ci/build.sh编译成功，使用脚本build-rel/bin/run_tests.sh也能跑过，但是单独执行python3 ../tests/cvcuda/python/test_opxxxx.py会失败，报错ModuleNotFoundError: No module named 'cvcuda'

**Comment by wzw773828204** [comment]
需要添加环境变量，把nvcv跟cvcuda两个so库的路径添加到PYTHONPATH
我通过编辑vi ~/.bashrc，把
export PYTHONPATH=/dataset/projects/ws_nh_algorithm/Cv-Cuda/CV-CUDA-0.2.0-alpha/build-rel/lib/python:$PYTHONPATH添加到~/.bashrc


#PythonPath
export PYTHONPATH=/dataset/projects/ws_nh_algorithm/Cv-Cuda/CV-CUDA-0.2.0-alpha/build-rel/lib/python:$PYTHONPATH
当然/dataset/projects/ws_nh_algorithm/Cv-Cuda/路径要改成你自己的路径

**Comment by yang0907** [comment]
> 需要添加环境变量，把nvcv跟cvcuda两个so库的路径添加到PYTHONPATH 我通过编辑vi ~/.bashrc，把 export PYTHONPATH=/dataset/projects/ws_nh_algorithm/Cv-Cuda/CV-CUDA-0.2.0-alpha/build-rel/lib/python:$PYTHONPATH添加到~/.bashrc
> 
> #PythonPath export PYTHONPATH=/dataset/projects/ws_nh_algorithm/Cv-Cuda/CV-CUDA-0.2.0-alpha/build-rel/lib/python:$PYTHONPATH 当然/dataset/projects/ws_nh_algorithm/Cv-Cuda/路径要改成你自己的路径
可以成功了，根据cvcuda_test_python这个脚本里面的python版本号执行，python3.8 xxx.py

**Comment by wzw773828204** [comment]
> 我通过删除/usr/bin/ld:/home/dali/Projects/CV-CUDA/src/util/stubs/下面的.so文件，重新下载源码上的.so文件，复制到src/util/stubs/目录下，重新编译就通过了。我也不知道啥原理。。。可能是下载下来的整个zip里面的so文件有损


请问你有遇到过其他问题吗
Line 679: '' failed: no kernel image is available for execution on the device
跑里面的cvcuda.resize跟其他的图像预处理函数都会报错
麻烦加个v聊聊

**Comment by ZJLi2013** [comment]
`pip install nvcv_python-0.3.0_Beta-cp310-cp310-linux_x86_64.whl 
export PYTHONPATH="/usr/local/lib/python3.10/dist-packages/nvcv_python"
 `
fix the issue
