### ISSUE TITLE
什么时候支持windows平台

### ISSUE THREAD

**Issue by jay19453** [CVCUDA/CV-CUDA#110]
如题，各位工程师什么时候支持windows平台，很迫切

**Comment by pmikolajczyk** [comment]
This is on the roadmap, will update with version.

Can you share your usecase?

**Comment by bhaefnerNV** [comment]
Hi @jay19453,
Thank you for your interest in CVCUDA.
This seems to be a duplicate of [92](https://github.com/CVCUDA/CV-CUDA/issues/92). Hence, we will close this ticket and kindly ask you track the mentioned issue.
