### ISSUE TITLE
[BUG] Issue with python include order and pyTorch library.

### ISSUE THREAD

**Issue by pmikolajczyk** [CVCUDA/CV-CUDA#113]
In certain configurations there will be a segfault when importing torch in python.  This will only happen when NVCV or CV-CUDA is imported prior to torch.

WARs to this issue:
   1. Include torch first in your python script.
   2. Recompile CV-CUDA with dynamic linking to the libstdc++ this can be done by removing the following line:
```
-static-libstdc++
```
from: 
```
/python/CMakeLists.txt
/scr/util/CMakeLists.txt
```
and recompiling.

The issue is described in more detail here:
https://github.com/pytorch/pytorch/issues/109923

**Comment by dlesage-nvidia** [comment]
Closing as the issue was fixed with the Beta 3 release: https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.5.0-beta
