### ISSUE TITLE
[QUESTION]希望多一些c++ 做分割的示例

### ISSUE THREAD

**Issue by dulishu1999** [CVCUDA/CV-CUDA#117]
**What is your question?**

**Comment by dlesage-nvidia** [comment]
Thank you for your interest in CV-CUDA! 
Could you clarify your request please? Are you asking for specific C++ samples?

**Comment by bhaefnerNV** [comment]
Hi @dulishu1999,

we will close this issue due to inactivity. Please feel free if the problem persists.
