### ISSUE TITLE
[QUESTION] Is there letterbox function used in yolov5/v8?

### ISSUE THREAD

**Issue by HaoLiuHust** [CVCUDA/CV-CUDA#123]
**What is your question?**
in yolov5 or v8, there is an letterbox preprocess, dose cv-cuda has this preprocesser?

**Comment by leyankon** [comment]
HI @HaoLiuHust  
I also encountered this problem. Resize will cause image distortion. How did you solve this problem? Does cv-cuda provide letterbox function?

**Comment by lazylazypig** [comment]
any updates?

**Comment by ghost** [comment]
@lazylazypig 
hi， i also meet the same problem, how do you solve it?
