### ISSUE TITLE
[QUESTION] How to convert a nvcv.Tensor to cvcuda.Image?

### ISSUE THREAD

**Issue by HaoLiuHust** [CVCUDA/CV-CUDA#124]
**What is your question?**
I want to use padandstack function, it needs ImageBatchVarShape input, how can I construct it with a list of Tensor?

**Comment by HaoLiuHust** [comment]
found as_image method

**Comment by wuyanzhang** [comment]
> found as_image method

你好，能否给一个成功的例子。我这边转失败了。

**Comment by HaoLiuHust** [comment]
> > found as_image method
> 
> 你好，能否给一个成功的例子。我这边转失败了。 TypeError: as_image(): incompatible function arguments. The following argument types are supported: 1. (buffer: nvcv.ExternalBuffer, format: nvcv.Format = nvcv.Format.NONE) -> nvcv.Image 2. (buffer: list[object] = [], format: nvcv.Format = nvcv.Format.NONE) -> nvcv.Image
> 
> Invoked with: <nvcv.Tensor shape=(600, 640, 3) dtype=uint8>

不好意思，有些久了，后来没用这个，不太记得了
