### ISSUE TITLE
[BUG] Failed to use cvcuda with torch dataloader

### ISSUE THREAD

**Issue by scse-l** [CVCUDA/CV-CUDA#13]
**Describe the bug**
When I try to use cvcuda with torch dataloader, I get an exception: 

`TypeError: cannot pickle 'nvcv.Tensor' object`

Is there any solution to use cvcuda with torch dataloader ? Or will it be compatible with torch dataloader in future?

**Comment by scse-l** [comment]
I also tried to use torch.Tensor returned by torch.dataloader to generate cvcuda.Tensor. It raises exception: `RuntimeError: NVCV_ERROR_INVALID_ARGUMENT: Pitch of dimension 3 must be == 4 (packed), but it is 1048576`. 
You can use following code to reproduce:
```python
import cvcuda
import torch
from torchvision.datasets import FakeData
import torch.utils.data
from torchvision import transforms

fd = FakeData(1000, (3, 512, 512), 10, transforms.ToTensor())
dl = torch.utils.data.DataLoader(fd)
idx, (imgs, labels) = next(enumerate(dl))
imgs = imgs.cuda()
imgs = imgs.permute([0, 2, 3, 1])
cvcuda.as_tensor(imgs, "NHWC")
```

**Comment by milesp-nvidia** [comment]
Hi @scse-l, if you can run the `print_env.sh` script and post the results here.

**Comment by complexfilter** [comment]
I have seen similar error.

**Comment by tp-nan** [comment]
It seems that only contiguous torch.Tensor is supported:

`cvcuda.as_tensor(imgs.contiguous(), "NHWC")
`

**Comment by bhaefnerNV** [comment]
@scse-l, thank you for your interest in CV-CUDA.

Indeed for constructing a CVCUDA tensor object, we expect the strides to be constant for each dimension. As pointed out by @tp-nan in [his answer](https://github.com/CVCUDA/CV-CUDA/issues/13#issuecomment-1864011218), this can be achieved via having a contiguous in memory tensor.

We'll close this issue for now, feel free to reopen if this did not resolve your problem.
