### ISSUE TITLE
[FEATURE]is there a plan to  reimplement kernel with triton language 

### ISSUE THREAD

**Issue by zjd1988** [CVCUDA/CV-CUDA#137]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem. Ex. I wish I could use CV-CUDA to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by dlesage-nvidia** [comment]
Hi, thank you for your interest in CV-CUDA!
Could you give us more information on your use case? I assume that you are referring to using CV-CUDA Nvidia Triton Inference servers.
