### ISSUE TITLE
[FEATURE] Please provide a setup.py script to generate python whl package

### ISSUE THREAD

**Issue by L-Block-C** [CVCUDA/CV-CUDA#138]

**Comment by shiremathNV** [comment]
@L-Block-C - thanks for reaching out with your request. We will look into this and get back to you soon. Are there specific version(s) of Python that you wish to generate .whl package(s) for?

**Comment by L-Block-C** [comment]
Thanks， and it‘s not about py version ，i want to add some code and generate my whl @shiremathNV

**Comment by L-Block-C** [comment]
I wrote my own setup.py, but it will package all .so files under build/lib/. How can I package only the specified two .so files?
```
packages=[''],
package_data={'': ["cvcuda.cpython-*.so","nvcv.cpython-*.so"]},
```

**Comment by bhaefnerNV** [comment]
Hi @L-Block-C,
Thank you for your interest in CVCUDA.
With [release 0.6.0](https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.6.0-beta), we started to provide standalone python wheels, including tooling and documentation to generate them. The setup.py file can be found [here](https://github.com/CVCUDA/CV-CUDA/blob/main/python/setup.py.in); it might also be interesting to have a look at the [build_wheel.sh script](https://github.com/CVCUDA/CV-CUDA/blob/main/python/build_wheels.sh) in the same folder.
Additionally, we we automatically build python wheels when building in release mode, have a look [here ](https://github.com/CVCUDA/CV-CUDA#build-from-source) for further details.
We will close this issue for now. Please reopen if further questions arise.
