### ISSUE TITLE
[FEATURE] Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [CVCUDA/CV-CUDA#140]
**Describe the feature**
@shiremath,
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd video cards if cuda code is optimized, and speed up work on amd.

**Comment by shiremathNV** [comment]
Hello @GermanAizek ,

Thanks for your feature request. 
Currently, the CV-CUDA team's NVIDIA's priority is to optimize the CUDA kernels under the operators and supporting other features to enable our developers to get better performance on and utilization of NVIDIA GPUs.
