### ISSUE TITLE
[QUESTION]  Is that DLPack buffer's data type must have at most 4 lanes?

### ISSUE THREAD

**Issue by ElinLiu0** [CVCUDA/CV-CUDA#142]
I am currently rewrite my OpenCV CPU pipeline into fully CUDA one.When i trying to using `cvcuda.nms()` function,i preprocess the input Tensors using below code:
```python
# Convert to boxes dtype to 16bit Signed Integer
boxes = boxes.to(torch.int16)
scores = scores.to(torch.float16)
class_ids = class_ids.to(torch.int16)
print(f"BBoxes shape: {boxes.shape}")
print(f"Scores shape: {scores.shape}")
print(f"Class IDs shape: {class_ids.shape}")
boxes_nvcv = cvcuda.as_tensor(boxes,"XYWH")
scores_nvcv = cvcuda.as_tensor(scores)
class_ids_nvcv = cvcuda.as_tensor(class_ids)


indices = cvcuda.nms(
    src = boxes_nvcv,
    scores = scores_nvcv,
    iou_threshold = self.iouThres,
    score = class_ids_nvcv
)
```
It then raised this error:
```bash
BBoxes shape: torch.Size([34, 4])
Scores shape: torch.Size([34])
Class IDs shape: torch.Size([34])
Traceback (most recent call last):
  File "/home/elin/modelTraining/Apps/GPUPipe/test.py", line 18, in <module>
    postprocessedImage = processor.postProcess(image,TRTOutput)
  File "/home/elin/modelTraining/Apps/GPUPipe/VideoProcessorGPU.py", line 92, in postProcess
    scores_nvcv = cvcuda.as_tensor(scores)
RuntimeError: DLPack buffer's data type must have at most 4 lanes
```

But according to the [document](https://cvcuda.github.io/modules/python_modules.html?highlight=nms#cvcuda.nms),it seems the scores Tensor and class_ids Tensor should be 1d Tensor.
That's really weird and confused😂

**Comment by 631068264** [comment]
Hello @ElinLiu0  

How did you solve this ?  I get same error when I use torch.float16  in cvcuda

**Comment by ElinLiu0** [comment]
> Hello [@ElinLiu0](https://github.com/ElinLiu0)
> 
> How did you solve this ? I get same error when I use torch.float16 in cvcuda

You can refer my code here:https://github.com/ElinLiu0/StudentBehaviorDetection/blob/gpuPipe/VideoProcessorGPUCVCUDA.py

Arround 72 line.It's quite dumb but i use reshape to `forcing` add a new dimension on tensor data.🤣
