### ISSUE TITLE
Is there a corresponding example for FindContour, and how to obtain the contour coordinates?[QUESTION]

### ISSUE THREAD

**Issue by zhkuo24** [CVCUDA/CV-CUDA#148]
**What is your question?**
Hello, I am using the `cvcuda::FindContours` operator. Could you please provide an example for reference? I am currently unable to obtain the coordinates of the contour points. Thank you.

**Comment by dlesage-nvidia** [comment]
Hi @zhkuo24 , thank you very much for your interest in CV-CUDA.
Please note that the FindContours has been pulled from the most recent release to allow us to work offline on resolving certain of its issues. 
The option to obtain the coordinates has been added as a feature request.

In the meantime, if you are still using FindContours from an older release, an example use can be found in its unit test: https://github.com/CVCUDA/CV-CUDA/blob/feat/milesp/release_0-6-6/tests/cvcuda/system/TestOpFindContours.cpp
