### ISSUE TITLE
No module named 'nvcv'

### ISSUE THREAD

**Issue by DLTensor** [CVCUDA/CV-CUDA#15]
I have installed "nvcv_python-0.2.0_alpha-cp38-cp38-linux_x86_64.whl" in environment (python3.8.3 / cuda11.0 / ubuntu18.04).
and then I code "import nvcv", but this message "no module named 'nvcv'" posts

**Comment by wzw773828204** [comment]
https://github.com/CVCUDA/CV-CUDA/issues/10

**Comment by wzw773828204** [comment]
https://github.com/CVCUDA/CV-CUDA/issues/11

**Comment by bhaefnerNV** [comment]
As indicated by @wzw773828204, this issue seems to be resolved in #11.

We will address improving our install instructions for python in a future release.
