### ISSUE TITLE
Is there any official API documentation for Python?

### ISSUE THREAD

**Issue by pengxin233** [CVCUDA/CV-CUDA#158]
https://cvcuda.github.io/modules/python_modules.html

The Python api document in this link is empty, and only the C++ and C api documents are seen.

**Comment by dlesage-nvidia** [comment]
Thank you for the notification! We have updated the [documentation ](https://cvcuda.github.io/modules/python_modules.html#cv-cuda-python-api-reference).
Note that we will be working on improving, especially modularizing that documentation in a future release.

Thank you for your interest in CV-CUDA!
