### ISSUE TITLE
[QUESTION] nvjpeg support batch decode with diffferent resolutions, but torch don't support

### ISSUE THREAD

**Issue by mingting** [CVCUDA/CV-CUDA#17]
```
# sample code, https://github.com/CVCUDA/CV-CUDA/blob/release_v0.2.x/samples/segmentation/python/inference.py#L414

image_tensor_list = decoder.batch_decode(data_batch)

# Convert the list of tensors to a tensor itself.
image_tensors = torch.stack(image_tensor_list)
```

if decode jpeg with batch decode mode, torch.stack api report error.

RuntimeError: stack expects each tensor to be equal size, but got [454, 500, 3] at entry 0 and [355, 500, 3] at entry 1

any good idea for support batch decode with different resolutions?

**Comment by shiremathNV** [comment]
Hello @mingting ,

Thanks for your question. Could you please run the print_env.sh script in the root directory of the repo and post the results here?

**Comment by mingting** [comment]
> Hi @mingting,
> 
> This is somehow expected. As `image_tensor_list` is a list of tensors of different sizes (each representing a different image), you cannot convert it to a single N-dimensional (where N is a batch size) Torch tensor as `torch.stack` expects all the tensors in the list (images) to be uniform. You need to resize/crop them first.

Hi @JanuszL 
thanks for reply.
this code snippet is get from sample code,  https://github.com/CVCUDA/CV-CUDA/blob/release_v0.2.x/samples/segmentation/python/inference.py#L414
I thought the sample code supported different size jpeg decoding.
seems like this kind of limitation is expected.
I will resize/crop them first.

BR.
Mingting

**Comment by mingting** [comment]
> > Hi @mingting,
> > This is somehow expected. As `image_tensor_list` is a list of tensors of different sizes (each representing a different image), you cannot convert it to a single N-dimensional (where N is a batch size) Torch tensor as `torch.stack` expects all the tensors in the list (images) to be uniform. You need to resize/crop them first.
> 
> We can not resize/crop data before decoding. Because jpeg data is a kind of compressed data. Sample of batch decode with different resolutions can refer to https://github.com/NVIDIA/CUDALibrarySamples/tree/master/nvJPEG/nvJPEG-Decoder-MultipleInstances. @mingting

OK, get it, thanks for reply.

BR.
Mingting

**Comment by mingting** [comment]
> Hello @mingting ,
> 
> Thanks for your question. Could you please run the print_env.sh script in the root directory of the repo and post the results here?

Hi @shiremathNV 
I cannot access my workstation right now, sorry for I cannot share the result right now.
I will do resize/crop after decoding and before send the list into torch.
thanks for the reply.

BR.
Mingting

**Comment by JanuszL** [comment]
@mingting,

I mean you need to resize/crop them after decoding (probably one by one) and then when they are uniform stack them to one Torch tensor.
