### ISSUE TITLE
Is there a windows version?

### ISSUE THREAD

**Issue by wenyuxiang19** [CVCUDA/CV-CUDA#177]
as the title suggests

**Comment by bhaefnerNV** [comment]
Hi @wenyuxiang19,

Thank you for your interest in CVCUDA.
Currently, we don't have native Windows support, however CV-CUDA is compatible with WSL2 with Ubuntu >= 20.04.
We are considering adding native Windows OS support in a future release.

Furthermore, this feature on Windows support seems to be a duplicate of https://github.com/CVCUDA/CV-CUDA/issues/92. Hence, we will close this ticket and kindly ask you track the mentioned issue.
