### ISSUE TITLE
[BUG] RuntimeError: pybind11_object_dealloc(): Tried to deallocate unregistered instance!

### ISSUE THREAD

**Issue by wuyanzhang** [CVCUDA/CV-CUDA#188]
When I try to use CV-CUDA resize with multithreading involved on it (high number of threads), i got runtime error on it:
RuntimeError: pybind11_object_dealloc(): Tried to deallocate unregistered instance!

cvcuda-cu11：0.9.0b0

**Comment by dlesage-nvidia** [comment]
Hi @wuyanzhang, thank you for your bug report!
Would you mind trying out the newly released v0.11 (https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.11.0-beta)?
We have upgraded the pybind11 version, which includes bug fixes for the kind of errors you're reporting here.

**Comment by yondonfu** [comment]
FWIW I previously saw this error a few times and after upgrading to v0.11 I haven't encountered it.

**Comment by wuyanzhang** [comment]
> Hi @wuyanzhang, thank you for your bug report! Would you mind trying out the newly released v0.11 (https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.11.0-beta)? We have upgraded the pybind11 version, which includes bug fixes for the kind of errors you're reporting here.

After trying out the newly released v0.11, I meet these errors again.
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance!
@dlesage-nvidia

**Comment by wuyanzhang** [comment]
> Hi @wuyanzhang, thank you for your bug report! Would you mind trying out the newly released v0.11 (https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.11.0-beta)? We have upgraded the pybind11 version, which includes bug fixes for the kind of errors you're reporting here.

After upgrading to v0.11, this error disappeared. Thanks for your reply!

**Comment by dlesage-nvidia** [comment]
Awesome, thank you for your feedback.
I will close that issue for the time being, please reopen it if you observe the error again.
