### ISSUE TITLE
[QUESTION] error: there are no arguments to '__float2int_rz' 

### ISSUE THREAD

**Issue by Bingo851** [CVCUDA/CV-CUDA#19]
I got an error when I use cv cuda, anyone can help me about this?

`warp.cuh:585:26: error: there are no arguments to '__float2int_rz' that depend on a template parameter, so a declaration of '__float2int_rz' must be available [-fpermissive]`

**Comment by shiremathNV** [comment]
Hello @Bingo851 ,

We are looking into this. Could you please run the `print_env.sh` script in the root directory of the repo and post the results here?

**Comment by Bingo851** [comment]
Hi @shiremathNV , here is the results

`<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit 0ecbaa978ec5cbd9513aa581d19b02389a75d175 (HEAD -> release_v0.2.x, tag: v0.2.0-alpha, origin/release_v0.2.x, origin/main, origin/HEAD)
     Author: Miles Price <milesp@nvidia.com>
     Date:   Wed Dec 21 16:30:28 2022 -0800

     feat: initializing GitHub repo with tested CV-CUDA operators.
     **git submodules***
     5ab508a01f9eb089207ee87fd547d290da39d015 3rdparty/googletest (release-1.8.0-3127-g5ab508a0)
     0694ec6a15863bff2e0ea5efe07c78de39b9a33c 3rdparty/pybind11 (v2.10.2)

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
     NAME="Ubuntu"
     VERSION="20.04.5 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.5 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux eaaf2b3da9b6 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Wed Jan 11 03:32:37 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA RTX A6000    Off  | 00000000:01:00.0  On |                  Off |
     | 31%   60C    P2    84W / 300W |   1729MiB / 48677MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  NVIDIA TITAN X ...  Off  | 00000000:02:00.0 Off |                  N/A |
     | 23%   22C    P8     8W / 250W |      4MiB / 12196MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   39 bits physical, 48 bits virtual
     CPU(s):                          8
     On-line CPU(s) list:             0-7
     Thread(s) per core:              2
     Core(s) per socket:              4
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           94
     Model name:                      Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
     Stepping:                        3
     CPU MHz:                         4180.580
     CPU max MHz:                     4300.0000
     CPU min MHz:                     800.0000
     BogoMIPS:                        7999.96
     Virtualization:                  VT-x
     L1d cache:                       128 KiB
     L1i cache:                       128 KiB
     L2 cache:                        1 MiB
     L3 cache:                        8 MiB
     NUMA node0 CPU(s):               0-7
     Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Mitigation; Microcode
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.24.0

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2022 NVIDIA Corporation
     Built on Wed_Sep_21_10:33:58_PDT_2022
     Cuda compilation tools, release 11.8, V11.8.89
     Build cuda_11.8.r11.8/compiler.31833905_0

     ***Python***
     /usr/bin/python
     Python 3.8.10

     ***Environment Variables***
     PATH                            : /opt/tensorrt/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /usr/local/bin/pip
     Package             Version
     ------------------- --------------------
     appdirs             1.4.4
     certifi             2019.11.28
     chardet             3.0.4
     dbus-python         1.2.16
     distro-info         0.23ubuntu1
     graphsurgeon        0.4.6
     idna                2.8
     Mako                1.2.4
     MarkupSafe          2.1.1
     numpy               1.23.4
     Pillow              9.3.0
     pip                 22.3.1
     platformdirs        2.5.4
     polygraphy          0.43.1
     protobuf            4.21.9
     pycuda              2022.1
     PyGObject           3.36.0
     python-apt          2.0.0+ubuntu0.20.4.8
     pytools             2022.1.12
     requests            2.22.0
     requests-unixsocket 0.2.0
     setuptools          45.2.0
     six                 1.14.0
     tensorrt            8.5.1.7
     typing_extensions   4.4.0
     uff                 0.6.9
     unattended-upgrades 0.1
     urllib3             1.25.8
     wheel               0.34.2

</pre></details>`

**Comment by pmikolajczyk** [comment]
closing as stale
