### ISSUE TITLE
[FEATURE]libtorch interface

### ISSUE THREAD

**Issue by tp-nan** [CVCUDA/CV-CUDA#20]
At this moment, CudaBuffer can be converted to torch.Tensor through `__cuda_array_interface__`. However, sometimes we have to use libtorch(at::Tensor/torch::Tensor). Is it possible to make a libtorch interface for nvcv::Tensor/ITensor ?

**Comment by tp-nan** [comment]
Another benefit of using libtorch bindings is it makes it easier to integrate and utilize PyTorch's Gpu memory reuse facilities , which are associated with CUDA streams, This is important in cloud-based services

**Comment by SongDabao** [comment]
> At this moment, CudaBuffer can be converted to torch.Tensor through `__cuda_array_interface__`. However, sometimes we have to use libtorch(at::Tensor/torch::Tensor). Is it possible to make a libtorch interface for nvcv::Tensor/ITensor ?


I'm having the same problem now, how did you solve it? Thanks！

**Comment by tp-nan** [comment]
> > At this moment, CudaBuffer can be converted to torch.Tensor through `__cuda_array_interface__`. However, sometimes we have to use libtorch(at::Tensor/torch::Tensor). Is it possible to make a libtorch interface for nvcv::Tensor/ITensor ?
> 
> I'm having the same problem now, how did you solve it? Thanks！

I wrote a libtorch interface here  [toNvcvTensor and fromNvcvTensor ](https://github.com/torchpipe/torchpipe/blob/9fdf43bd9758dd84c7deef1c3d41e3002203c518/torchpipe/csrc/cvcuda/src/cvcuda_helper.cpp#L203C12-L203C26), for Tensor2NvTensor and NvTensor2Tensor backends

**Comment by shiremathNV** [comment]
@dlesage-nvidia @pmikolajczyk
