### ISSUE TITLE
[FEATURE]  When will the sample of pytorch train with cv-cuda be given?

### ISSUE THREAD

**Issue by GxjGit** [CVCUDA/CV-CUDA#22]
We see the samples of inference,   but the  samples of train is not found.   How to replace _pil decode + torchvision transform_ by _nvjepg decode + cvcuda transfrom_   in torch trainning?    For example,  how can I use cu-cuda to modify this code: https://github.com/pytorch/examples/blob/main/imagenet/main.py

**Comment by shiremathNV** [comment]
Hello @GxjGit - have you looked into DALI for your training workflow needs? DALI is NVIDIA's accelerated solution for data loading and augmentation in DL training. In a future release, DALI will support a CV-CUDA in the backend for image and computer vision operations thus making it easy to use CV-CUDA in inference and thus ensuring replicable results in training and inference. 
More on DALI: https://developer.nvidia.com/dali

**Comment by JanuszL** [comment]
Hi @GxjGit,

You can even now use DALI for inference thanks [the dedicated TRITON backend](https://github.com/triton-inference-server/dali_backend) so you are sure the same data processing is applied during training as during the inference.
