### ISSUE TITLE
[BUG]TypeError: as_tensor(): incompatible function arguments. The following argument types are supported

### ISSUE THREAD

**Issue by tigerzjh** [CVCUDA/CV-CUDA#25]
**Describe the bug**
cvcuda_input_tensor = cvcuda.as_tensor(image_tensors, "NHWC")
TypeError: as_tensor(): incompatible function arguments. The following argument types are supported:
    1. (buffer: nvcv.cuda.Buffer, layout: Optional[nvcv.TensorLayout] = None) -> nvcv.Tensor
    2. (image: nvcvpy::priv::Image) -> nvcv.Tensor

code

import torch
import torchnvjpeg
import time
import cv2
import numpy as np
import torchvision
import cvcuda
from multiprocessing.pool import ThreadPool

image_data = open("images/cat.jpg", 'rb').read()

# parallel decode
batch_size, cpu_threads = 8, 8
data_list = [image_data for _ in range(batch_size)]
decoder_list = [torchnvjpeg.Decoder() for _ in range(batch_size)]
pool = ThreadPool(cpu_threads)
def run(args):
    decoder, data = args
    return decoder.decode(data)
time_s = time.time()
for i in range(1000):
    image_tensor_list = pool.map(run, zip(decoder_list, data_list))
print('parallel torchnvjpeg decode gpu cost {} for batch {} '.format(time.time() - time_s, batch_size))
pool.close()        # 关闭进程池，不再接受新的进程
pool.join()  

# Convert the list of tensors to a tensor itself.
image_tensors = torch.stack(image_tensor_list)
print(type(image_tensors))
cvcuda_input_tensor = cvcuda.as_tensor(image_tensors, "NHWC")

# Resize to the input network dimensions
time_s = time.time()
for i in range(1000):
    cvcuda_resize_tensor = cvcuda.resize(cvcuda_input_tensor, 
                                         (batch_size, 224, 224, 3, ), 
                                         cvcuda.Interp.LINEAR, )
print('cvcuda resize gpu cost {} for batch {}'.format(time.time() - time_s), batch_size)
    
cvcuda_preprocessed_tensor = cvcuda.reformat(cvcuda_resize_tensor, "NCHW")

# Run inference on the preprocessed input
torch_preprocessed_tensor = torch.as_tensor(cvcuda_preprocessed_tensor.cuda(), device="cuda")

**Comment by pmikolajczyk** [comment]
Resolved in alpha.1 release
