### ISSUE TITLE
[FEATURE] Interoperablility with DeepStream

### ISSUE THREAD

**Issue by Paskin** [CVCUDA/CV-CUDA#27]
I wish I could use CV-CUDA to write a custom DeepStream components - when the data being processed remains on GPU.

**Comment by shiremathNV** [comment]
Thanks @Paskin for your feedback. This is a feature that are we are looking to add in a future release. Could you share a little bit about the type of application(s) that you are developing with DeepStream>

**Comment by Paskin** [comment]
Our application does IVA and employs multi-channel video decoding, object detection, classification, tracking etc - to detect  fraudulent/criminal events in retail. One of the features, where such an integration can simplify porting to DeepStream - is camera tampering detection (covering, turning off-scene, blinding with light, disconnection from DVR etc), when the frames continue to arrive. It is done today with some proprietary + OpenCV code, which we will be more than happy to offload to GPU.

**Comment by milesp-nvidia** [comment]
We are working with NVIDIA DeepStream. Please stay tuned for future releases.

**Comment by thiagoribeirodamotta** [comment]
Has the code showed at the GTC video session been shared?
