### ISSUE TITLE
cannot find -lcvcuda [BUG]

### ISSUE THREAD

**Issue by fuma8** [CVCUDA/CV-CUDA#28]
I try CV-CUDA samples, but error is occurred when I run this command. anyone can help me?
```
./scripts/build_samples.sh
```
![image](https://user-images.githubusercontent.com/105157899/212002446-ce01bed4-3b42-4200-ae1f-221cbca6c80b.png)

**Comment by xiyuecangxin** [comment]
```
find / | grep libcvcuda
```
Then 
```
ln -s {your libcvcuda.so} /usr/bin/libcvcuda.so
```

**Comment by shiremathNV** [comment]
@xiyuecangxin ,

Could you please run the `print_env.sh` script in the root directory of the repo and post the results here?

**Comment by DLTensor** [comment]
find / | grep libcvcuda
Then
n -s {your libcvcuda.so} /usr/lib/x86_64-linux-gnu/libcvcuda.so

**Comment by pmikolajczyk** [comment]
Closing as no response
