### ISSUE TITLE
[FEATURE] publish cv-cuda in pypi

### ISSUE THREAD

**Issue by ristoh** [CVCUDA/CV-CUDA#30]
**Is your feature request related to a problem? Please describe.**

Instead of building locally and doing an install from a local wheel, could you publish cv-cuda at pypi to make it available in an easier way to broader python developers?

**Describe the solution you'd like**

Publish cv-cuda at pypi.org

**Comment by Ely-S** [comment]
Agreed, a pypi package would be very helpful to devs like myself.

I would love to contribute a continuous delivery configuration that automatically publishes this as a python package. This would be pretty simple to do using GitHub Actions. Does that sound like a good solution to the maintainers? If so, I can start on it.

**Comment by milesp-nvidia** [comment]
Hey @ristoh! Thanks for the Feature Request here. Having PyPi packages for CV-CUDA is definitely one of the features that would make CV-CUDA available to a broader audience.

@Ely-S That sounds like an awesome idea! Show us what you got! We are very open to incorporating ideas from the open source community.

**Comment by Ely-S** [comment]
Building from the source distribution takes over an hour on my system, so my recommendation is to ship the prebuilt wheel (.whl) through pypi. There is a python wheel mentioned in the README, but it wasn't generated when running `ci/build.sh` or `cpack .` Do you know how the wheel was created?

**Comment by Ely-S** [comment]
update: I was able to build a wheel for this package, but it doesn't meet PyPi's requirement that linux_86 wheels be portable across common linux distributions.

**Comment by milesp-nvidia** [comment]
Thanks for that @Ely-S, I will note this as an issue and we will move forward to fix that.

**Comment by Ely-S** [comment]
Looking into it further, here are the allowed dependancies for a python wheel. https://peps.python.org/pep-0513/#the-manylinux1-policy .

Maybe it would make sense to distribute this library as a .deb package through a PPA instead of PyPi, because all the dependancies can also be specified as Ubuntu packages.

**Comment by milesp-nvidia** [comment]
Hey @Ely-S, I notice that you have the names: cvcuda and cvcuda-test reserved on pypi. CV-CUDA plans to public this program to pypi soon. Are you able to turn those names over to us?

**Comment by shiremathNV** [comment]
Hello @Ely-S - thanks for you interest in CV-CUDA on PyPi. We are looking into adding official support for CV-CUDA on PyPi this year. We would really appreciate your support to make this possible by providing us access to the cvcuda repo name which is currently authored by you. If you are open to a discussion on this matter, please let us know. Thanks for your co-operation.
