### ISSUE TITLE
[QUESTION]CV-CUDA支持ubuntu arm64的版么？可以运行在边缘设备上，例如：Orin或者更早的NX？

### ISSUE THREAD

**Issue by cmffire** [CVCUDA/CV-CUDA#33]
CV-CUDA支持ubuntu arm64的版么？可以运行在边缘设备上，例如：Orin或者更早的NX？

**Comment by mkhadatare** [comment]
Hi @cmffire ,
Currently CV_CUDA not supported for ARM64. 
We are adding support in next release CV-CUDA (Beta). Keep you posted.

**Comment by milesp-nvidia** [comment]
We will officially support cross compilations of CV-CUDA for AMR64 devices in future releases.
