### ISSUE TITLE
[QUESTION] Why the number of bytes from Requirements is larger than expected?

### ISSUE THREAD

**Issue by wang-xinyu** [CVCUDA/CV-CUDA#37]
Hi team,

In the samples, I saw that the buffer size is calculated from Requirements, and the number is larger than expected.

For example, a 100x100 RGB8 tensor, the size should be 100x100x3 = 30000, but the size calculated from Requirements is larger than 30000.

```
nvcv::Tensor::Requirements reqs = nvcv::Tensor::CalcRequirements(1, {100, 100}, nvcv::FMT_RGB8);
int64_t buf_size = CalcTotalSizeBytes(nvcv::Requirements{reqs.mem}.cudaMem());
```

And if I don't use Requirements, but allocate a 100x100x3 buffer directly, seems there is no issue, I already tested ResizeOp and CustomCrop.

Can you please elaborate why do we need to use Requirements to calculate the buffer size?

If I don't use Requirements, but allocate a 100x100x3 buffer directly, will there be any potential risk?

Thanks in advance.

**Comment by mkhadatare** [comment]
Hi [wang-xinyu](https://github.com/wang-xinyu),

The buffer size calculated using data type  formats example FMT_RGB8 (8bit), there are some image has 16 and other formats.

To support different types of [data type](https://github.com/CVCUDA/CV-CUDA/blob/release_v0.2.x/src/nvcv_types/include/nvcv/DataType.h) calculate requirement is needed.
