### ISSUE TITLE
nv-cuda 项目的意义

### ISSUE THREAD

**Issue by linhuifj** [CVCUDA/CV-CUDA#38]
opencv也支持cuda，[可以用cv::cuda:xxxx 这样的操作](https://opencv.org/platforms/cuda/)，你的这个库和它相比速度会快很多吗？

**Comment by ShiyangZhang** [comment]
cv::cuda:resize 和cv::resize的结果应该不一定一样。CVCUDA是保证一样的

**Comment by linhuifj** [comment]
其实这没有很好的回答我的问题。如果希望CV-cuda有很多人用，应该好好回答下，我们为什么需要cv-cuda？

**Comment by shiremathNV** [comment]
@linhuifj - CV-CUDA team is focused on performance. The operators in CV-CUDA will be hand optimized for high performance on GPUs (current focus is on data center grade GPUs like T4, A10, A100, etc.). We are seeing speed ups in performance in comparison to other CPU-based implementations across the operators in CV-CUDA 0.2.0.
