### ISSUE TITLE
[QUESTION]Must use gcc>=11.1 to compile CV-CUDA, you're using GNU-9.3.0

### ISSUE THREAD

**Issue by ruanjiyang** [CVCUDA/CV-CUDA#39]
**What is your question?**
type "ci/build.sh"
and I got the following error:
Must use gcc>=11.1 to compile CV-CUDA, you're using GNU-9.3.0

but my gcc is already 11.3 now.
gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

how to solve it? thanks lot.

**Comment by mkhadatare** [comment]
Hi [ruanjiyang](https://github.com/ruanjiyang)

Can you run following steps and re-run it

```
sudo apt-get update && sudo apt-get install -y --no-install-recommends gcc-11 g++-11 
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
sudo update-alternatives --set gcc /usr/bin/gcc-11	
sudo update-alternatives --set g++ /usr/bin/g++-11
```

**Comment by milesp-nvidia** [comment]
This should work as of CV-CUDA alpha
