### ISSUE TITLE
[QUESTION] Performance comparison with NPP?

### ISSUE THREAD

**Issue by clpl** [CVCUDA/CV-CUDA#4]
I was pleasantly surprised to see such a good project.
I know that nvidia also has another gpu image processing library: NVIDIA 2D Image And Signal Performance Primitives (NPP)
Is there a performance comparison between cv-cuda and nppi, such as a benchmark?

**Comment by shiremathNV** [comment]
Hello @clpl 
We will consider including a performance comparison between the two (CV-CUDA and NPP) in a future release. Are there specific operators that are of interest to you for this comparison? What is you intended use case for CV-CUDA?

**Comment by milesp-nvidia** [comment]
We will provide more performance information as the product develops.
