### ISSUE TITLE
[QUESTION] CMake Error

### ISSUE THREAD

**Issue by ruanjiyang** [CVCUDA/CV-CUDA#40]
when I do ci/build_docs.sh build

I meet the following error. help please, and thanks.

.......
-- Configuring done
CMake Error at samples/common/CMakeLists.txt:23 (add_library):
  Target "nvcv_samples_common" links to target "TensorRT::nvinfer" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at samples/classification/CMakeLists.txt:21 (add_executable):
  Target "nvcv_samples_classification" links to target "TensorRT::nvinfer"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at samples/cropandresize/CMakeLists.txt:22 (add_executable):
  Target "nvcv_samples_cropandresize" links to target "TensorRT::nvinfer" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by mkhadatare** [comment]
Hi [ruanjiyang](https://github.com/ruanjiyang)

For sample buidling there additional package to [Install TensorRT](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing) 
`pip3 install torch torchvision`

can you run the print_env.sh script and post here.

**Comment by basaltzhang** [comment]
I got a same error, after installed tensorrt by [tar file installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar), still got this error.

**Comment by milesp-nvidia** [comment]
This issue was fixed in alpha.

**Comment by Hongyuan-Liu** [comment]
I also encountered this problem, and my solution was to set the installation path of TensorRT in ConfigTensorRT.cmake (I installed TensorRT using a tar file), in ConfigTensorRT.cmake file add code: set(TRT_ROOT "/opt/TensorRT-8.6.1.6"), my tensrort install path is /opt/TensorRT-8.6.1.6
