### ISSUE TITLE
Hardware Decoder not supported

### ISSUE THREAD

**Issue by bxkdstar123** [CVCUDA/CV-CUDA#42]
Tesla T4 执行run_samples.sh ,报错不支持硬件解码
Hardware Decoder not supported. Falling back to default backend

那些GPU支持 ？

**Comment by maheshkha** [comment]
Hi [bxkdstar123](https://github.com/bxkdstar123),
Tesla T4 does not support Hardware decoder then it will fall back to software based decoding. 
This is expected.
If you test on [NVIDIA Ampere (A100) GPU](https://developer.nvidia.com/blog/leveraging-hardware-jpeg-decoder-and-nvjpeg-on-a100/) has hardware decoder then your decoder performance is higher.

**Comment by mkhadatare** [comment]
Hi [bxkdstar123](https://github.com/bxkdstar123),
Tesla T4 does not support Hardware decoder so it will fall back to software decoder.

If you have[ NVIDIA Ampere (A100)](https://developer.nvidia.com/blog/leveraging-hardware-jpeg-decoder-and-nvjpeg-on-a100/) who has dedidated hardware decoder can enhance the performance.
