### ISSUE TITLE
yolox.cpp 依赖CV-CUDA，编译出错

### ISSUE THREAD

**Issue by bxkdstar123** [CVCUDA/CV-CUDA#43]
错误信息：

In file included from /root/CV-CUDA/src/nvcv_types/include/nvcv/ImageFormat.hpp:27,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/IImageData.hpp:24,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/IImage.hpp:22,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/Image.hpp:21,
                 from /root/YOLOX/demo/TensorRT/cpp/yolox.cpp:13:
/root/CV-CUDA/src/nvcv_types/include/nvcv/ColorSpec.hpp: In member function 'nvcv::ColorSpace nvcv::ColorSpec::colorSpace() const':
/root/CV-CUDA/src/nvcv_types/include/nvcv/ColorSpec.hpp:230:23: error: cannot convert 'NVCVColorSpace' to 'nvcv::ColorSpace' in initialization
  230 |     return ColorSpace{out};
      |                       ^~~
      |                       |
      |                       NVCVColorSpace
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/yolox.dir/build.make:76: CMakeFiles/yolox.dir/yolox.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/yolox.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by mkhadatare** [comment]
Hi [bxkdstar123](https://github.com/bxkdstar123)

Can you run  the print_env.sh script and post here.

**Comment by bxkdstar123** [comment]
> Hi [bxkdstar123](https://github.com/bxkdstar123)
> 
> Can you run the print_env.sh script and post here.

[env.txt](https://github.com/CVCUDA/CV-CUDA/files/10541587/env.txt)

**Comment by bxkdstar123** [comment]
直接用 g++-11 , 也会出现同样的问题。 


g++-11 -g -Wall -std=c++14 -O3 -I./ -I/usr/local/cuda/include -I/root/TensorRT/include -I/usr/local/include/opencv4 -I/root/CV-CUDA/samples -I/root/CV-CUDA/src/nvcv_types/include -I/root/CV-CUDA/src/cvcuda/include  -c -o yolox.o yolox.cpp

In file included from /root/TensorRT/include/NvInferLegacyDims.h:53,
                 from /root/TensorRT/include/NvInfer.h:53,
                 from yolox.cpp:9:
/root/TensorRT/include/NvInferRuntimeCommon.h: In member function 'virtual bool nvinfer1::IGpuAllocator::deallocate(void*)':
/root/TensorRT/include/NvInferRuntimeCommon.h:1484:19: warning: 'virtual void nvinfer1::IGpuAllocator::free(void*)' is deprecated [-Wdeprecated-declaration ]
 1484 |         this->free(memory);
      |         ~~~~~~~~~~^~~~~~~~
/root/TensorRT/include/NvInferRuntimeCommon.h:1415:33: note: declared here
 1415 |     TRT_DEPRECATED virtual void free(void* const memory) noexcept = 0;
      |                                 ^~~~
In file included from /root/CV-CUDA/src/nvcv_types/include/nvcv/ImageFormat.hpp:27,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/IImageData.hpp:24,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/IImage.hpp:22,
                 from /root/CV-CUDA/src/nvcv_types/include/nvcv/Image.hpp:21,
                 from yolox.cpp:13:
/root/CV-CUDA/src/nvcv_types/include/nvcv/ColorSpec.hpp: In member function 'nvcv::ColorSpace nvcv::ColorSpec::colorSpace() const':
/root/CV-CUDA/src/nvcv_types/include/nvcv/ColorSpec.hpp:230:23: error: cannot convert 'NVCVColorSpace' to 'nvcv::ColorSpace' in initialization
  230 |     return ColorSpace{out};
      |                       ^~~
      |                       |
      |                       NVCVColorSpace
yolox.cpp: In function 'float* blobFromImage(cv::Mat&)':
yolox.cpp:226:26: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
  226 |     for (size_t c = 0; c < channels; c++)
      |                        ~~^~~~~~~~~~
yolox.cpp:228:31: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
  228 |         for (size_t  h = 0; h < img_h; h++)
      |                             ~~^~~~~~~
yolox.cpp:230:34: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
  230 |             for (size_t w = 0; w < img_w; w++)
      |                                ~~^~~~~~~
yolox.cpp: In function 'void doInference(nvinfer1::IExecutionContext&, float*, float*, int, cv::Size)':
yolox.cpp:446:9: warning: unused variable 'mBatchSize' [-Wunused-variable]
  446 |     int mBatchSize = engine.getMaxBatchSize();
      |         ^~~~~~~~~~
yolox.cpp: In function 'int main(int, char**)':
yolox.cpp:537:21: warning: 'void nvinfer1::IExecutionContext::destroy()' is deprecated [-Wdeprecated-declarations]
  537 |     context->destroy();
      |     ~~~~~~~~~~~~~~~~^~
In file included from /root/TensorRT/include/NvInfer.h:54,
                 from yolox.cpp:9:
/root/TensorRT/include/NvInferRuntime.h:1960:25: note: declared here
 1960 |     TRT_DEPRECATED void destroy() noexcept
      |                         ^~~~~~~
yolox.cpp:538:20: warning: 'void nvinfer1::ICudaEngine::destroy()' is deprecated [-Wdeprecated-declarations]
  538 |     engine->destroy();
      |     ~~~~~~~~~~~~~~~^~
In file included from /root/TensorRT/include/NvInfer.h:54,
                 from yolox.cpp:9:
/root/TensorRT/include/NvInferRuntime.h:1485:25: note: declared here
 1485 |     TRT_DEPRECATED void destroy() noexcept
      |                         ^~~~~~~
yolox.cpp:539:21: warning: 'void nvinfer1::IRuntime::destroy()' is deprecated [-Wdeprecated-declarations]
  539 |     runtime->destroy();
      |     ~~~~~~~~~~~~~~~~^~
In file included from /root/TensorRT/include/NvInfer.h:54,
                 from yolox.cpp:9:
/root/TensorRT/include/NvInferRuntime.h:716:25: note: declared here
  716 |     TRT_DEPRECATED void destroy() noexcept

**Comment by mkhadatare** [comment]
Hi @bxkdstar123 
Can you share more details about `yolox.cpp` or short description what you are trying to do here. 
Also provide small reproduciable code so we will debug and address the issue.

**Comment by bxkdstar123** [comment]
问题解决了， -std=c++20  就可以了

**Comment by mkhadatare** [comment]
Thank you!

**Comment by silaopi** [comment]
I got same problem here. I try to set -std=c++20 or c++17, and the compile process was sucessful. But after I try to deserialize the tensorrt engine, programe failed with this information.
```
! Debugger was unable to disassemble function containing address 0x0000000000000000: Cannot access memory at address 0x0
```
And everything worked correctly before I add any cvcuda head files to my program.

System env is here:
[env.txt](https://github.com/CVCUDA/CV-CUDA/files/10554447/env.txt)

**Comment by silaopi** [comment]
It's very strange that cvcuda seems doesnot work with fp16 quantization. I convert resnet50.onnx to tensorrt engine using --fp16, and do inference using official sample nvcv_samples_classification, here are the results:

- without --fp16

```
$ ./bin/nvcv_samples_classification -e ./models/resnet50.engine -i ./assets/tabby_tiger_cat.jpg -l ./models/imagenet-classes.txt -b 1
Hardware Decoder not supported. Falling back to default backend
Processing: ./assets/tabby_tiger_cat.jpg
Total decoding time: 0.00202445 (s)
Avg decoding time per image: 0.00202445 (s)
Avg images per sec: 493.962
Avg decoding time per batch: 0.00202445 (s)
Deserializing engine from: ./models/resnet50.engine
Time for Preprocess : 50.4006 ms
Time for Inference : 6.36192 ms
Time for Postprocess : 0.072896 ms

Classification results for batch 0 
Class : tiger cat , Score : 0.864282
Class : tabby, tabby cat , Score : 0.088545
Class : Egyptian cat , Score : 0.026870
Class : lynx, catamount , Score : 0.010006
Class : tiger, Panthera tigris , Score : 0.003220
(base) 
```

- with --fp16 (same problem with my previous commit, and my own model still doesn't work with or without --fp16)

```
$ ./bin/nvcv_samples_classification -e ./models/resnet50_fp16.engine -i ./assets/tabby_tiger_cat.jpg -l ./models/imagenet-classes.txt -b 1
Hardware Decoder not supported. Falling back to default backend
Processing: ./assets/tabby_tiger_cat.jpg
Total decoding time: 0.00182886 (s)
Avg decoding time per image: 0.00182886 (s)
Avg images per sec: 546.788
Avg decoding time per batch: 0.00182886 (s)
[1]    514200 segmentation fault (core dumped)  ./bin/nvcv_samples_classification -e ./models/resnet50_fp16.engine -i  -l  -b
(base) 

```
