### ISSUE TITLE
[BUG] Two bugs in Resize

### ISSUE THREAD

**Issue by mzchtx** [CVCUDA/CV-CUDA#44]
We found two bugs in the resize op, as shown in the figure below:

- The first one is located in the [resize_NN_quad_alignread function](https://github.com/CVCUDA/CV-CUDA/blob/release_v0.2.x/src/cvcuda/priv/legacy/resize.cu#L155); this bug will be triggered when the interpolation parameter of the resize op is **cvcuda.Interp.NEAREST**, and **scale_x > 4.0**.

- The second one is located in the [resize_bicubic_quad_alignread function](https://github.com/CVCUDA/CV-CUDA/blob/release_v0.2.x/src/cvcuda/priv/legacy/resize.cu#L447-L463); this bug will be triggered when the interpolation parameter of the resize op is **cvcuda.Interp.CUBIC** and **scale_x > 4.0**.

We randomly selected 100 images from ImageNet and our internal datasets and compared the results with OpenCV's resize. The modification in the image below can solve the above problems.

![image](https://user-images.githubusercontent.com/37564754/215642252-8eb4af88-9aeb-4cdb-b607-8a531c66c697.png)

**Comment by pmikolajczyk** [comment]
Thank you for the contribution! We are investigating the issue you have brought up and taking inspiration from your contribution to see if it can address it"

**Comment by milesp-nvidia** [comment]
This issue was fixed in [Beta](https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.3.0-beta)
