### ISSUE TITLE
Hardware Decoder not supported. Falling back to default backend

### ISSUE THREAD

**Issue by bxkdstar123** [CVCUDA/CV-CUDA#46]
Tesla T4 卡不支持硬件JPEG解码 ？

**Comment by mkhadatare** [comment]
NVIDIA Tesla T4 - no on chip (Hardware JPEG) decoder - [specs](https://www.nvidia.com/en-us/data-center/tesla-t4/)
NVIDIA A30 or A100 - on chip (Hardware JPEG) decoder - [specs](https://www.nvidia.com/en-us/data-center/products/a30-gpu/)

Tesla T4 error Hardware Decoder not supported. Falling back to default backend say program using software based JPEG decoder to decode the image. There is no difference in decoded images.
