### ISSUE TITLE
Build from Source ERROR , run 'ci/build.sh' get error

### ISSUE THREAD

**Issue by lsx66** [CVCUDA/CV-CUDA#49]
/usr/bin/ld:/workspace/CV-CUDA/src/util/stubs/libdl-2.17_stub.so: file format not recognized; treating as linker script
/usr/bin/ld:/workspace/CV-CUDA/src/util/stubs/libdl-2.17_stub.so:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvcv_types/CMakeFiles/nvcv_types.dir/build.make:313: lib/libnvcv_types.so.0.2.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:741: src/nvcv_types/CMakeFiles/nvcv_types.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by basaltzhang** [comment]
make sure you are in CV-CUDA dir, then run
`git lfs pull`

**Comment by inocsin** [comment]
Fix by https://github.com/CVCUDA/CV-CUDA/issues/26
