### ISSUE TITLE
Support nvidia's jetson series

### ISSUE THREAD

**Issue by xjhaz** [CVCUDA/CV-CUDA#5]
I want to use it on nvidia's xavier nx, but it seems that it is only support the x86 platform.  The GPU of the jetson series is much stronger than the CPU. I hope that it can be used on the platform of the jetson series in the future to speed up the processing speed of my own opencv program.

**Comment by shiremathNV** [comment]
Thank for your interest in CV-CUDA for use with NVIDIA Xavier NX device. CV-CUDA is currently focused on supporting data center-grade GPU use cases. Have you looked into the VPI library? This is NVIDIA's accelerated library for embedded devices and discrete GPUs, with computer vision and image processing algorithms that are optimized for performance on the different backends available on a Jetson platform (GPU, PVA, VIC, etc.). Please refer to the link to learn more about VPI:  https://developer.nvidia.com/embedded/vpi
