### ISSUE TITLE
All components are too new!!

### ISSUE THREAD

**Issue by basaltzhang** [CVCUDA/CV-CUDA#51]
CUDA Driver >= 11.7 (Not tested on 12.0)
GCC >= 11.0
Python >= 3.7
cmake >= 3.22

Difficult to compile from source code, I have to update **ALL** my tools to fit these minimum versions. Are these really needed?

Example, if I don't need #include <compare> to use c++20 <=> , I can use gcc version 8, am i right?

**Comment by lji72** [comment]
+1

**Comment by lji72** [comment]
It's difficult to use in some project with lower gcc.

**Comment by edric1261234** [comment]
especially GCC

**Comment by shiremathNV** [comment]
Hello, Thanks for your feedback on the minimum versions.

On the new release that went live this week (v0.3.0), we have lowered the minimum versions on CUDA toolkit and GCC.
* CUDA Toolkit >= 11.3 support for core library build and run
*  GCC >= 9.0 supported for core library build and run

Hope this helps. For lower GCC version than 9.0, will using the gcc-9 pre-builds to link against meet your requirements?
@basaltzhang @lji72 @edric1261234

**Comment by davidhopper2003** [comment]
> Hello, Thanks for your feedback on the minimum versions.
> 
> On the new release that went live this week (v0.3.0), we have lowered the minimum versions on CUDA toolkit and GCC.
> 
> * CUDA Toolkit >= 11.3 support for core library build and run
> * GCC >= 9.0 supported for core library build and run
> 
> Hope this helps. For lower GCC version than 9.0, will using the gcc-9 pre-builds to link against meet your requirements? @basaltzhang @lji72 @edric1261234

According to the GCC and CUDA versions you gave, it cannot be compiled successfully on Ubuntu 20.04. Please refer to my post: https://github.com/CVCUDA/CV-CUDA/issues/95

**Comment by chencuber** [comment]
yes，very difficult to integrate into current working project! 

Ubuntu22.04 is too high, even nvidia ngc container only support Ubuntu20.04 with cuda<12。
just suggest that all building（not just core library） uses Ubuntu20.04 with cuda<=11.6 and gcc >= 9.0。
