### ISSUE TITLE
no need to call 'abort' when checkKernelErrors failed

### ISSUE THREAD

**Issue by ShiyangZhang** [CVCUDA/CV-CUDA#55]
https://github.com/CVCUDA/CV-CUDA/blob/304c79be4b894a0bb2eaa66ac5010c95c2a46eb1/src/cvcuda/priv/legacy/CvCudaUtils.cuh#L1080

It's too dangerous to call `abort` when checkKernelErrors failed. An exception is enough.

**Comment by rodolfoschulz** [comment]
Hi Shiyang, once a cuda kernel fails, all subsequent cuda kernels will fail, that's how the cuda driver handles this. Since this is a non-recoverable error that shouldn't have happened in the first place, we decided to abort the application.

**Comment by rodlima78** [comment]
Hi Shiyang, errors originating from cuda kernel execution are non-recoverable. For this reason we've decided to abort instead of throwing an exception. The only way to recover from these errors is to restart the process.

**Comment by tp-nan** [comment]
> Hi Shiyang, errors originating from cuda kernel execution are non-recoverable. For this reason we've decided to abort instead of throwing an exception. The only way to recover from these errors is to restart the process.

"errors originating from cuda kernel execution are non-recoverable"   ：Could you please confirm if this is correct? Are some kernel errors, such as incorrect dim settings or similar, unrecoverable?

**Comment by tp-nan** [comment]
CUDA itself allows kernel errors without breaking the program, so it may be better to retain this behavior
