### ISSUE TITLE
[FEATURE]再容器里面跑samples,跑不起来，报错误如下

### ISSUE THREAD

**Issue by pengyige123** [CVCUDA/CV-CUDA#56]
./bin/nvcv_samples_classification: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bin/nvcv_samples_classification)
./bin/nvcv_samples_classification: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bin/nvcv_samples_classification)
./bin/nvcv_samples_classification: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lib/libnvcv_samples_common.so)

**Comment by pmikolajczyk** [comment]
Looks like a environment configuration fault, can you run print_env.sh and provide output?

**Comment by mkhadatare** [comment]
Hi @pengyige123 

Can you update your OS to Ubuntu 20.04 and verify that you will not see this issue.
