### ISSUE TITLE
nvcv_python3.9-configure error

### ISSUE THREAD

**Issue by jimurk** [CVCUDA/CV-CUDA#58]
When i run "ci/build.sh" to build the project, what i got is as following:

-- Configuring done (2.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ice/projects/CV-CUDA/build-rel
[0/2 1 0.000s] Re-checking globbed directories...
[217/286 6 477.067s] Performing configure step for 'nvcv_python3.9'
FAILED: python3.9/stamp/nvcv_python3.9-configure /home/ice/projects/CV-CUDA/build-rel/python3.9/stamp/nvcv_python3.9-configure 
cd /home/ice/projects/CV-CUDA/build-rel/python3.9/build && /usr/local/bin/cmake -DCMAKE_INSTALL_PREFIX=/home/ice/projects/CV-CUDA/build-rel -Dnvcv_types_ROOT=/home/ice/projects/CV-CUDA/build-rel/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=true -DCMAKE_BUILD_RPATH_USE_ORIGIN=true -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_PREFIX=/opt/nvidia/cvcuda0 -DCMAKE_MODULE_PATH=/home/ice/projects/CV-CUDA/build-rel/cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ice/projects/CV-CUDA/build-rel/lib -DNVCV_TYPES_SOURCE_DIR=/home/ice/projects/CV-CUDA/src/nvcv_types -DPYBIND11_SOURCE_DIR=/home/ice/projects/CV-CUDA/3rdparty/pybind11 -DDLPACK_SOURCE_DIR= -DWARNINGS_AS_ERRORS=OFF -DENABLE_COMPAT_OLD_GLIBC=ON -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 -DPYTHON_VERSION=3.9 -GNinja -S /home/ice/projects/CV-CUDA/python -B /home/ice/projects/CV-CUDA/build-rel/python3.9/build && /usr/local/bin/cmake -E touch /home/ice/projects/CV-CUDA/build-rel/python3.9/stamp/nvcv_python3.9-configure
-- The CXX compiler identification is GNU 11.1.0
-- The C compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-11 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- pybind11 v2.10.2 
-- Found PythonInterp: /usr/local/bin/python3.9 (found suitable version "3.9.7", minimum required is "3.9") 
-- Found PythonLibs: /usr/local/lib/libpython3.9.a
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.8.89") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at mod_nvcv/CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source "dlpack" which is not an existing directory.

-- Configuring incomplete, errors occurred!
[222/286 1 496.916s] Building CXX object tests/nvcv_types/cudatools_system/CMakeFiles/nvcv_test_cudatools_system.dir/TestFullTensorWrap.cpp.o
ninja: build stopped: subcommand failed.

This project is built on ubuntu 20.04&CUDA 11.8&g++ 11&python 3.9. Does anyone has an idea about this error?

**Comment by milesp-nvidia** [comment]
Can you please provide the output of the ``print_env.sh`` script?

**Comment by pmikolajczyk** [comment]
Likely you are not pulling a sub-module. run or see init_repo.sh in the root.

**Comment by mkhadatare** [comment]
Hi @jimurk 

From the log - it says dlpack not found.

Can you init the submodule pointed here https://github.com/dmlc/dlpack/tree/ca4d00ad3e2e0f410eeab3264d21b8a39397f362 
Pull the all the repos.
