### ISSUE TITLE
[BUG 必现]当我的设备有多卡的时候，我的图像不是用主显卡decode时候，cvcuda的接口会报cudaErrorIllegalAddress: an illegal memory access was encountered，并且产生core文件

### ISSUE THREAD

**Issue by pengyige123** [CVCUDA/CV-CUDA#59]
['/data/juicefs_ai_camera/public_data/imagenet_folder/train/n01440764/n01440764_10026.JPEG']
Traceback (most recent call last):
  File "para.py", line 610, in <module>
    main()
  File "para.py", line 153, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "para.py", line 301, in main_worker
    image_batch = cvcuda.ImageBatchVarShape(len(data_batch))
RuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Error in atexit._run_exitfuncs:
RuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'nvjpeg::ExceptionJPEG'
  what():  Error in the CUDA API call
Aborted (core dumped)

**Comment by pmikolajczyk** [comment]
Can you provide more info on images, number images, formats and if possible the part of the code where you are hitting the failure?

**Comment by sunjun** [comment]
我也遇到了，解决方案就是调用算子的时候，保证算子操作的数据在一张卡上
比如   resizeOp(_cudaStream, rgbTensor, resizedTensor, NVCV_INTERP_LINEAR);
rgbTensor和resizedTensor占用的显存要在一张显卡上
如果不在一张卡上可以调用cudamemcpy先拷贝下，显卡Unified Virtual Addressing支持的话cudamemcpy支持跨显卡操作

**Comment by xxmiprai** [comment]
说一下我的解决方法，以供参考：在使用cvcuda函数的线程中，使用`cudart.cudaSetDevice(gpu_id)`设置一下要使用的GPU。验证方法：在调用cvcuda的函数中，可以使用`cudart.cudaGetDevice(gpu_id)`看一下返回的是几号GPU，如果它和你的图像不在一个GPU，调用就会出错。

**Comment by mkhadatare** [comment]
Hi @xxmiprai @pengyige123 
Can you set the visible [CUDA_VISIBLE_DEVICES](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/)
e.g., to set os.environ['CUDA_DEVICE'] = '1' will make GPU:1 as the default device.

**Comment by Lyan-ing** [comment]
We meet same question, can you give me some suggestions?
"Warning CVCUDA cleanup may be incomplete due to: cudaErrorIllegalAddress: an illegal memory access was encountered"

the codes
image1 = torch.from_numpy(cv2.imread(image1_path, cv2.IMREAD_GRAYSCALE)).to(device='cuda').unsqueeze(2)
    image2 =  torch.from_numpy(cv2.imread(image2_path, cv2.IMREAD_GRAYSCALE)).to(device='cuda').unsqueeze(2)

    nv_img1 = cvcuda.as_tensor(image1, 'HWC')
    a = cvcuda.sift(nv_img1)

    nv_img2 = cvcuda.as_tensor(image2, 'HWC')
    b = cvcuda.sift(nv_img2)

    c = cvcuda.match(a[2], b[2])
