### ISSUE TITLE
[QUESTION] Is the data quota for the repo reached?

### ISSUE THREAD

**Issue by Cayub1** [CVCUDA/CV-CUDA#66]
**What is your question?**
Is the Git LFS data quota for the repo reached? 

I cloned the repo, but I got an error stating: `batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. error: failed to fetch some objects from 'https://github.com/CVCUDA/CV-CUDA.git/info/lfs'`. So I am unable to get the Git LFS tracked files such as the `.so` files in `src/util/stubs` for running `ci/build.sh`. I've also tried cloning the repo again, ensuring that `git lfs install` has been ran, and I tried to get these files from the source code as well; however, they are Git LFS text pointers.

**Comment by sdwalker62** [comment]
Yeah I cannot download anything from git lfs either

**Comment by saikrishna2893** [comment]
Yeah we too cannot clone the repo.

**Comment by saikrishna2893** [comment]
> We will follow up, in the meantime as a workaround you should be able to download the repo as a .zip.

Yes we tried to download repo as a .zip file, but few packages like under /src/util/stubs could not be downloaded because of git lfs issue and are required for clean build. Is it possible to share a zip file with all the required files including the files in git lfs can be shared?

**Comment by Cayub1** [comment]
> > We will follow up, in the meantime as a workaround you should be able to download the repo as a .zip.
> 
> Yes we tried to download repo as a .zip file, but few packages like under /src/util/stubs could not be downloaded because of git lfs issue and are required for clean build. Is it possible to share a zip file with all the required files including the files in git lfs can be shared?

Yes, this is the case for me when I download and extract the .zip as well.

**Comment by milesp-nvidia** [comment]
Thank you for pointing this out. The issue with the repo is resolved at this moment.
