### ISSUE TITLE
install cvcuda python,  ModuleNotFoundError: No module named 'cvcuda'

### ISSUE THREAD

**Issue by sunnyheart008205** [CVCUDA/CV-CUDA#69]
1. sudo apt-get install -y ./nvcv-lib-0.2.1_alpha-cuda11-x86_64-linux.deb ./nvcv-dev-0.2.1_alpha-cuda11-x86_64-linux.deb
![image](https://user-images.githubusercontent.com/34880744/232696813-9b09edb6-59e3-4cea-ac08-ba1c585b3b49.png)
2. pip install nvcv_python-0.2.1_alpha-cp38-cp38-linux_x86_64.whl
![image](https://user-images.githubusercontent.com/34880744/232697008-aae4a8bf-8059-4971-8663-b7a6bcd9a3f3.png)
cuda version is 11.4
![image](https://user-images.githubusercontent.com/34880744/232697629-50c97a9f-baba-4a7f-b925-cda08f78bb90.png)

two steps are successful!
but the problem still exists
![image](https://user-images.githubusercontent.com/34880744/232697414-a3b67c9d-cea3-47c4-94ba-3a7d340de56b.png)
Could you help me? please.

**Comment by mkhadatare** [comment]
Hi @sunnyheart008205 
Can you follow these steps https://github.com/CVCUDA/CV-CUDA/tree/release_v0.3.x/samples#working-with-pre-builts-binaries 
`export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python3.8/dist-packages/python"`

Hope this will help.
