### ISSUE TITLE
[QUESTION]随机处理的OP支持吗？类似torchvision.transforms.RandomAffine这样的

### ISSUE THREAD

**Issue by LinGeLin** [CVCUDA/CV-CUDA#7]
**What is your question?**
好像没有看到随机处理的OP，有这样的用法吗？或者以后会支持吗？

**Comment by LinGeLin** [comment]
或者怎么样实现类似的功能？

**Comment by LinGeLin** [comment]
考虑出中文文档吗？

**Comment by shiremathNV** [comment]
Hello @LinGeLin , 
Thanks for your question. Random processing is not a feature available for operators in the Alpha. We are looking into supporting this feature in a future release. Are there specific operators for which you are looking for random processing support?

**Comment by LinGeLin** [comment]
RandomResizedCrop
RandomRotation
RandomHorizontalFlip
RandomBlur

and so on

**Comment by milesp-nvidia** [comment]
Thank you for your response here. If you are asking for these operations as they apply to DNN training, have you considered [DALI](https://developer.nvidia.com/dali)?
