### ISSUE TITLE
[FEATURE] How to convert from YUV420SP(nv12) to BRG8?

### ISSUE THREAD

**Issue by fan-chao** [CVCUDA/CV-CUDA#70]
Hi, 
We now have got NV12 data including image info, e.g. image.width and image.height, after decoding video. The NV12 data is at gpu now. We want to convert this NV12 data to BGR data, but it failed to create tensor from NV12 data like the following code. The function nvcv::Tensor::CalcRequirements only support NCHW or NHWC but not YUV like format. How 
to do it?

Thanks.

```
nvcv::Tensor::Requirements in_reqs = nvcv::Tensor::CalcRequirements(1, { pAVFrame->width, pAVFrame->height }, nvcv::FMT_NV12);

nvcv::TensorDataStridedCuda::Buffer in_buf;
std::copy(in_reqs.strides, in_reqs.strides + NVCV_TENSOR_MAX_RANK, in_buf.strides);
in_buf.basePtr = reinterpret_cast<NVCVByte*>(pAVFrame->data);

// Create a tensor buffer to store the data pointer and pitch bytes for each plane
nvcv::TensorDataStridedCuda in_data(nvcv::TensorShape{ in_reqs.shape, in_reqs.rank, in_reqs.layout }, nvcv::DataType{ in_reqs.dtype }, in_buf);

// TensorWrapData allows for interoperation of external tensor representations with CVCUDA Tensor.
nvcv::TensorWrapData in_tensor(in_data);
```

**Comment by YCG1** [comment]
static __device__ uint8_t cast(float value) {
        return value < 0 ? 0 : (value > 255 ? 255 : value);
    }

    static __global__ void convert_nv12_to_bgr_kernel(const uint8_t* y, const uint8_t* uv, int width, int height, int linesize, uint8_t* dst_bgr, int edge) {

        int position = blockDim.x * blockIdx.x + threadIdx.x;
        if (position >= edge) return;

        int ox = position % width;
        int oy = position / width;
        const uint8_t& yvalue = y[oy * linesize + ox];
        int offset_uv = (oy >> 1) * linesize + (ox & 0xFFFFFFFE);
        const uint8_t& u = uv[offset_uv + 0];
        const uint8_t& v = uv[offset_uv + 1];
        dst_bgr[position * 3 + 0] = cast(1.164f * (yvalue - 16.0f) + 2.018f * (u - 128.0f));
        dst_bgr[position * 3 + 1] = cast(1.164f * (yvalue - 16.0f) - 0.813f * (v - 128.0f) - 0.391f * (u - 128.0f));
        dst_bgr[position * 3 + 2] = cast(1.164f * (yvalue - 16.0f) + 1.596f * (v - 128.0f));
    }


    /////////////////////////////////////////////////////////////////////////
    void convert_nv12_to_bgr_invoke(
        const uint8_t* y, const uint8_t* uv, int width, int height, int linesize, uint8_t* dst, cudaStream_t stream) {

        int total = width * height;
        dim3 grid = grid_dims(total);
        dim3 block = block_dims(total);

        convert_nv12_to_bgr_kernel << <grid, block, 0, stream >> > (
            y, uv, width, height, linesize,
            dst, total
            );
    }

**Comment by milesp-nvidia** [comment]
Thank you for developing this code here! We are looking into this issue in color conversion.

**Comment by fan-chao** [comment]
Here, I use the following codes to create in_tensor for NV12 data, and it seems to work out.
`
// tag: Tensor Requirements
// Calculate the requirements for the NV12 uint8_t Tensor which include
// pitch bytes, alignment, shape  and tensor layout,
//Because batch operation is not support for NV12, so here we use FMT_U8 as format. Then Y plane and UV plane compose one plane.
nvcv::Tensor::Requirements in_reqs = nvcv::Tensor::CalcRequirements(1, { pAVFrame->width, pAVFrame->height * 3 / 2 }, nvcv::FMT_U8);

nvcv::TensorDataStridedCuda::Buffer in_buf;
std::copy(in_reqs.strides, in_reqs.strides + NVCV_TENSOR_MAX_RANK, in_buf.strides);
in_buf.basePtr = reinterpret_cast<NVCVByte*>(*pAVFrame->data);

// Create a tensor buffer to store the data pointer and pitch bytes for each plane
nvcv::TensorDataStridedCuda in_data(nvcv::TensorShape{ in_reqs.shape, in_reqs.rank, in_reqs.layout }, nvcv::DataType{ in_reqs.dtype }, in_buf);

// TensorWrapData allows for interoperation of external tensor representations with CVCUDA Tensor.
nvcv::TensorWrapData in_tensor(in_data);

// tag: Allocate Tensors for Crop and Resize
// Create a CVCUDA Tensor based on the crop window size.
cvtcolor_tensor_ = std::shared_ptr<nvcv::Tensor>(new nvcv::Tensor(1, { pAVFrame->width, pAVFrame->height }, nvcv::FMT_BGR8));

//init op
cvtcolor_op_ = std::make_shared<cvcuda::CvtColor>();

// tag: Executes the CvtColor operation on the given cuda stream
(*cvtcolor_op_)(reinterpret_cast<cudaStream_t>(cu_stream_), in_tensor, *cvtcolor_tensor_, NVCV_COLOR_YUV2BGR_NV12);
`

**Comment by pmikolajczyk** [comment]
new advanced color conversion operator will let you convert from NV12/21 to BGR/RGB, it was released in the Beta.2 release.
