### ISSUE TITLE
[BUG] Runtime Error when do Multithreading

### ISSUE THREAD

**Issue by tiketdatastanley** [CVCUDA/CV-CUDA#72]
When I try to use CV-CUDA resize with multithreading involved on it (high number of threads), sometimes the apps got runtime error on it

```RuntimeError: pybind11_object_dealloc(): Tried to deallocate unregistered instance!```

I use 2 core e2 machines and 1 Tesla T4 with number of threads is around 16. Is there any solution to use CV-CUDA parallelly?

**Comment by col-in-coding** [comment]
I got the same issue randomly, no idea

**Comment by L1aoXingyu** [comment]
I got the same issue when running multi-gpu training, no idea how to fix it.

**Comment by milesp-nvidia** [comment]
I are actively working on this bug.

**Comment by bhaefnerNV** [comment]
@tiketdatastanley this has been addressed in [CV-CUDA Release v0.3.1 Beta](https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.3.1-beta).

We'll close it for now, feel free to reopen if the issue persists.
