### ISSUE TITLE
[QUESTION] install version for cuda 11.6

### ISSUE THREAD

**Issue by trand2k** [CVCUDA/CV-CUDA#73]
Hi author, 
have any version for cuda 11.6 ?

**Comment by milesp-nvidia** [comment]
In general, CV-CUDA is built against [CUDA Toolkit 11.7](https://docs.nvidia.com/cuda/archive/11.7.0/), which should support backwards compatibility with [CUDA Toolkit 11.6](https://docs.nvidia.com/cuda/archive/11.6.0/).
