### ISSUE TITLE
video decode

### ISSUE THREAD

**Issue by Hongyuan-Liu** [CVCUDA/CV-CUDA#74]
I want to know if video decoding for streams like h264 and h265 can be done using CV-CUDA, and if it is possible, could you please provide a sample?

**Comment by YCG1** [comment]
nvidia video sdk

**Comment by milesp-nvidia** [comment]
Currently CV-CUDA does not natively support video encoding/decoding; however, you can use a library such as [NVIDIA Video Processing Framework](https://github.com/NVIDIA/VideoProcessingFramework) that provides both Python and C++ APIs.
