### ISSUE TITLE
[FEATURE] Release Python wheels for 3.9 and 3.11

### ISSUE THREAD

**Issue by ralbertazzi** [CVCUDA/CV-CUDA#78]
**Is your feature request related to a problem? Please describe.**
I wish I could use CV-CUDA pre-compiled wheels on Python 3.9 and Python 3.11, which are the Python versions our AI workloads are running in our company at the moment.

**Describe the solution you'd like**
cv-cuda wheels released on GitHub for Python 3.9 and Python 3.11

**Comment by milesp-nvidia** [comment]
Unfortunately we did not support Python 3.9 and 3.11 for this release, but we plan on supporting both interpreters in the next release.

**Comment by ralbertazzi** [comment]
Shouldn't the issue be closed once wheels have been released? 🤔
