### ISSUE TITLE
[FEATURE]Interoperability with DeepStream

### ISSUE THREAD

**Issue by Paskin** [CVCUDA/CV-CUDA#79]
I'd like to use CV-CUDA to write custom DeepStream components. To achieve that, it will be great to have a way to access NvBufSurface object and wrap it with nvcv::Tensor - as well as make resulting data available to DeepStream.

**Comment by milesp-nvidia** [comment]
At the time, we do not have the ability to wrap NvBufSurface and we do not currently have that scoped as part of our roadmap. Please see this GTC talk for a potential solution to interact with DeepStream data: [Advancing AI Applications with Custom GPU-Powered Plugins for NVIDIA DeepStream](https://www.nvidia.com/en-us/on-demand/session/gtcspring23-s51612/)

**Comment by Paskin** [comment]
This is pretty much what I was looking for. Thanks!
