### ISSUE TITLE
[BUG] Python whl 包不正确

### ISSUE THREAD

**Issue by scse-l** [CVCUDA/CV-CUDA#8]
**Describe the bug**
 Python whl 包安装后没有预期的 cvcuda 模块。

**Steps/Code to reproduce bug**
1. 下载 release 中的 nvcv_python-0.2.0_alpha-cp38-cp38-linux_x86_64.whl 文件
2. 执行 `pip install nvcv_python-0.2.0_alpha-cp38-cp38-linux_x86_64.whl` 安装 whl 包
3. 在 python 解释器中引入 cvcuda，出现提示 ModuleNotFoundError: No module named 'cvcuda'
<img width="679" alt="image" src="https://user-images.githubusercontent.com/11534916/209519649-91b3c95f-4016-4cae-abb6-6b3d4347b0c4.png">

**Expected behavior**
正确引入 cvcuda 模块。

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: pip
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**
希望在 ReadMe 里面补充下 python wheel 包的 build 方法。

**Comment by scse-l** [comment]
依次安装完 deb 包再安装 whl 包就可以了。

**Comment by aigoruan** [comment]
你好，请问在wsl2下可以安装成功吗，我这边也是按你说的步骤安装，但是失败了

**Comment by aigoruan** [comment]
可以安装成功，但是在python里import失败

**Comment by scse-l** [comment]
> 你好，请问在wsl2下可以安装成功吗，我这边也是按你说的步骤安装，但是失败了

没有，我 ubuntu 下安装的。
先下载两个 deb 包，分别安装，然后安装 python 包。另外从我的安装测试来看，跟 conda 不兼容，需要用原生的 python

**Comment by aigoruan** [comment]
嗯，我这边也解决了，默认的安装位置有问题，需要把.so文件移动一下

**Comment by scse-l** [comment]
> 嗯，我这边也解决了，默认的安装位置有问题，需要把.so文件移动一下

是兼容 conda Python 了嘛？

**Comment by aigoruan** [comment]
我没使用conda，就简单的把.so文件移动到库路径下，让python得到就可以了

**Comment by tigerzjh** [comment]
@aigoruan 移动哪些so, 移到哪里。我是用的tar包的方式。
![image](https://user-images.githubusercontent.com/23514705/211741756-366dd7a1-a530-4c46-8d57-931f0aa60611.png)

**Comment by Robintjhb** [comment]
> @aigoruan移动其中，移到哪里。我是用tar包的方式。 ![图像](https://user-images.githubusercontent.com/23514705/211741756-366dd7a1-a530-4c46-8d57-931f0aa60611.png)


我把opt/nvidia/cvcuda0/lib/x86_64-linux-gnu/python下的cvcuda.cpython-38-x86_64-linux-gnu.so，nvcv.cpython-38-x86_64-linux-gnu.so复制到 /usr/local/lib/python3.8/dist-packages/ 文件夹下import nvcv , cvcuda 起作用了，看了还是官方的那个  nvcv_python-*-*-linux_x86_64.whl 有问题呀

**Comment by cheft** [comment]
怎么移动，我全移动了还是一样的错
