### ISSUE TITLE
[QUESTION] yolo preprocess padding an resize accomplish

### ISSUE THREAD

**Issue by gentlebreeze1** [CVCUDA/CV-CUDA#80]
how to use the cvcuda library for padding and resizing images. @inocsin @ruoqianguo @milesp-nvidia

**Comment by gentlebreeze1** [comment]
anyone help

**Comment by milesp-nvidia** [comment]
There is a pad and stack operator as well as a resize op, but also a fused operator to do pad and resize the same time: [Pad&Stack](https://cvcuda.github.io/_exhale_api/group__NVCV__C__ALGORITHM__PADANDSTACK.html)
