### ISSUE TITLE
[QUESTION] Hardware Decoder not supported. Falling back to default backend

### ISSUE THREAD

**Issue by ylembot1** [CVCUDA/CV-CUDA#86]
when I run samples in cropandresize folder, a problem occured: 
> Hardware Decoder not supported. Falling back to default backend
> Processing: ../tabby_tiger_cat.jpg
> NVJPEG failure: '#4' at samples/common/NvDecoder.cpp:116

I modified the code like this：
![fda8a03beb4d01c41e4bb23461cda7cc](https://github.com/CVCUDA/CV-CUDA/assets/71958062/8e876f9a-8a8a-4370-9341-0a4ba3bd33c0)
it works，but the generated image is pure black. I think it's related to theproblem above

I find a doc that said: `Hardware accelerated JPEG decode is available on the following GPUs-A100,A30,H100`: https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-hardware-accelaration 
My GPU is Tesla T4. 
**May I ask if the above error occurred because my GPU hardware is not working properly？**
![image](https://github.com/CVCUDA/CV-CUDA/assets/71958062/b0722b42-dfcc-4fcc-aa6b-ef03b7375832)

**Comment by wuqingshan2010** [comment]
i have same question.how to solve it?

**Comment by mkhadatare** [comment]
Hello @ylembot1 
Thank you for reporting the issue.
nvJPEG Library supports CUDA SW based as well as NVIDIA HW-based JPEG decoding. 
But HW-based decoding is available only on A100, A30, and H100 GPUs.

In your case - NVIDIA T4 - does not support HW-based decoding so CUDA SW-based JPEG decoding.
NVJPEG failure: '#4' - either input image path bad JPEG or JPEG_NOT_SUPPORTED

Can you verify the input image ok.

**Comment by bhaefnerNV** [comment]
@ylembot1, this is a hardware-constraint related issue as per @mkhadatare response.
As suggested please consider using the appropriate GPU hardware that supports HW-based JPEG decoding.

**Comment by zhkuo24** [comment]
From what I've tested, it looks like GPU computing goes through a warm-up process. So, you should start timing from the second computation onwards.
