### ISSUE TITLE
cvcuda的pre_build包在哪里下载啊

### ISSUE THREAD

**Issue by wanhaipeng** [CVCUDA/CV-CUDA#9]
where is the pre_build pkg

**Comment by wanhaipeng** [comment]
nvcv-lib-0.2.0-cuda11-x86_64-linux.tar.xz ？？ 这个在哪里下载

**Comment by scse-l** [comment]
release 的 assets 里面 ：https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.2.0-alpha

**Comment by shiremathNV** [comment]
Yes, you should be able to find the pre-built packages here: https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.2.0-alpha 
Did this works for you? @wanhaipeng
