### ISSUE TITLE
[BUG] fatal error: cuosd.h: No such file or directory

### ISSUE THREAD

**Issue by optyang** [CVCUDA/CV-CUDA#90]
**Describe the bug**
`fatal error: cuosd.h: No such file or directory`, while `cuosd.h` is needed [here](https://github.com/CVCUDA/CV-CUDA/blob/release_v0.3.x/tests/cvcuda/system/OsdUtils.cuh#L21). 

The exact error log is as follows:
cvcuda/tests/cvcuda/system/OsdUtils.cuh:21:10: fatal error: cuosd.h: No such file or directory
   21 | #include "cuosd.h"
      |          ^~~~~~~~~
compilation terminated.

**Steps/Code to reproduce bug**
`ci/build.sh`

**Expected behavior**
`cuosd.h` should be included.

**Additional context**
In this [commit](https://github.com/CVCUDA/CV-CUDA/commit/fa0eab74785dba325ef69478a49b08ebca1ac713), the hard link to cuosd is removed. I guess `cuosd` should be added as a submodule in `3rdparty` but it wasn't.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit e4f97eeb9374d24bda30280de40211c6c8663f86 (HEAD -> release_v0.3.x, tag: v0.3.1-beta, origin/release_v0.3.x, origin/HEAD)
     Merge: b1b44d3 83f61ac
     Author: Miles Price <milesp@nvidia.com>
     Date:   Fri Jun 30 14:33:37 2023 -0700
     
     Merge branch 'main' into release_v0.3.x
     **git submodules***
     ca4d00ad3e2e0f410eeab3264d21b8a39397f362 3rdparty/dlpack (v0.8-1-gca4d00a)
     5ab508a01f9eb089207ee87fd547d290da39d015 3rdparty/googletest (release-1.8.0-3127-g5ab508a0)
     0694ec6a15863bff2e0ea5efe07c78de39b9a33c 3rdparty/pybind11 (v2.10.2)
     
     ***OS Information***
     CentOS Stream release 9
     PLATFORM=centos
     PLATFORM_VERSION=9
     NAME="CentOS Stream"
     VERSION="9"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="9"
     PLATFORM_ID="platform:el9"
     PRETTY_NAME="CentOS Stream 9"
     ANSI_COLOR="0;31"
     LOGO="fedora-logo-icon"
     CPE_NAME="cpe:/o:centos:centos:9"
     HOME_URL="https://centos.org/"
     BUG_REPORT_URL="https://bugzilla.redhat.com/"
     REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
     REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
     CentOS Stream release 9
     CentOS Stream release 9
     Linux devgpu018.ftw1.facebook.com 5.12.0-0_fbk13_zion_7455_gb24de3bdb045 #1 SMP Tue Mar 21 11:12:00 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Jul  5 08:18:43 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA PG509-210    On   | 00000000:11:00.0 Off |                    0 |
     | N/A   37C    P0    59W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   1  NVIDIA PG509-210    On   | 00000000:12:00.0 Off |                    0 |
     | N/A   41C    P0    63W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   2  NVIDIA PG509-210    On   | 00000000:48:00.0 Off |                    0 |
     | N/A   39C    P0    65W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   3  NVIDIA PG509-210    On   | 00000000:49:00.0 Off |                    0 |
     | N/A   41C    P0    63W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   4  NVIDIA PG509-210    On   | 00000000:86:00.0 Off |                    0 |
     | N/A   39C    P0    66W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   5  NVIDIA PG509-210    On   | 00000000:89:00.0 Off |                    0 |
     | N/A   40C    P0    69W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   6  NVIDIA PG509-210    On   | 00000000:C6:00.0 Off |                    0 |
     | N/A   39C    P0    60W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   7  NVIDIA PG509-210    On   | 00000000:C9:00.0 Off |                    0 |
     | N/A   41C    P0    65W / 330W |      3MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Address sizes:                   46 bits physical, 48 bits virtual
     Byte Order:                      Little Endian
     CPU(s):                          192
     On-line CPU(s) list:             0-191
     Vendor ID:                       GenuineIntel
     Model name:                      Intel(R) Xeon(R) Platinum 8339HC CPU @ 1.80GHz
     CPU family:                      6
     Model:                           85
     Thread(s) per core:              2
     Core(s) per socket:              24
     Socket(s):                       4
     Stepping:                        11
     Frequency boost:                 enabled
     CPU max MHz:                     1801.0000
     CPU min MHz:                     800.0000
     BogoMIPS:                        3600.00
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
     Virtualization:                  VT-x
     L1d cache:                       3 MiB (96 instances)
     L1i cache:                       3 MiB (96 instances)
     L2 cache:                        96 MiB (96 instances)
     L3 cache:                        132 MiB (4 instances)
     NUMA node(s):                    4
     NUMA node0 CPU(s):               0-23,96-119
     NUMA node1 CPU(s):               24-47,120-143
     NUMA node2 CPU(s):               48-71,144-167
     NUMA node3 CPU(s):               72-95,168-191
     Vulnerability Itlb multihit:     Not affected
     Vulnerability L1tf:              Not affected
     Vulnerability Mds:               Not affected
     Vulnerability Meltdown:          Not affected
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Not affected
     
     ***CMake***
     /home/user_name/local/miniconda3/envs/pytorch-3.10/bin/cmake
     cmake version 3.26.4
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /home/user_name/local/ccache/lib/g++
     g++ (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
     Copyright (C) 2021 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2023 NVIDIA Corporation
     Built on Fri_Jan__6_16:45:21_PST_2023
     Cuda compilation tools, release 12.0, V12.0.140
     Build cuda_12.0.r12.0/compiler.32267302_0
     
     ***Python***
     /home/user_name/local/miniconda3/envs/pytorch-3.10/bin/python
     Python 3.10.11
     
     ***Environment Variables***
     PATH                            : /home/user_name/local/miniconda3/envs/pytorch-3.10/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/usr/local/cuda/bin:/home/user_name/local/ccache/lib:/home/user_name/local/ccache/bin:/home/user_name/local/miniconda3/condabin:/home/user_name/.local/bin:/home/user_name/bin:/usr/share/Modules/bin:/usr/local/fbpkg/vscodefb/vscode-server/190/bin/remote-cli:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/ops/scripts:/usr/facebook/scripts:/usr/facebook/scripts:/usr/facebook/scripts/db:/usr/facebook/ops/scripts:/usr/facebook/scripts
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/user_name/local/miniconda3/envs/pytorch-3.10
     PYTHON_PATH                     :
     
     ***conda packages***
     conda ()
     {
     \local cmd="${1-__missing__}";
     case "$cmd" in
     activate | deactivate)
     __conda_activate "$@"
     ;;
     install | update | upgrade | remove | uninstall)
     __conda_exe "$@" || \return;
     __conda_reactivate
     ;;
     *)
     __conda_exe "$@"
     ;;
     esac
     }
     # packages in environment at /home/user_name/local/miniconda3/envs/pytorch-3.10:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                  2_kmp_llvm    conda-forge
     appdirs                   1.4.4              pyhd3eb1b0_0
     astunparse                1.6.3                      py_0
     audioread                 3.0.0           py310hff52083_1    conda-forge
     blas                      1.0                         mkl
     brotlipy                  0.7.0           py310h7f8727e_1002
     bzip2                     1.0.8                h7b6447c_0
     c-ares                    1.19.0               h5eee18b_0
     ca-certificates           2023.05.30           h06a4308_0
     ccache                    4.8.1                h1fcd64f_0    conda-forge
     certifi                   2023.5.7                 pypi_0    pypi
     cffi                      1.15.1          py310h5eee18b_3
     charset-normalizer        2.0.4              pyhd3eb1b0_0
     cmake                     3.26.4               h96355d8_0
     cryptography              39.0.1          py310h9ce1e76_2
     cuda-cudart               12.1.105                      0    nvidia
     cuda-cupti                12.1.105                      0    nvidia
     cuda-libraries            12.1.0                        0    nvidia
     cuda-nvrtc                12.1.105                      0    nvidia
     cuda-nvtx                 12.1.105                      0    nvidia
     cuda-opencl               12.2.53                       0    nvidia
     cuda-runtime              12.1.0                        0    nvidia
     cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
     cython                    0.29.35         py310h6a678d5_0
     dataclasses               0.8                pyh6d0b6a4_7
     decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
     expat                     2.4.9                h6a678d5_0
     ffmpeg                    4.2.2                h20bf706_0
     filelock                  3.9.0           py310h06a4308_0
     freetype                  2.10.4               h0708190_1    conda-forge
     fsspec                    2023.6.0                 pypi_0    pypi
     future                    0.18.3          py310h06a4308_0
     gettext                   0.21.1               h27087fc_0    conda-forge
     giflib                    5.2.1                h0b41bf4_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     gmpy2                     2.1.2           py310heeb90bb_0
     gnutls                    3.6.13               h85f3911_1    conda-forge
     idna                      3.4             py310h06a4308_0
     intel-openmp              2023.1.0         hdb19cb5_46305
     jinja2                    3.1.2           py310h06a4308_0
     joblib                    1.2.0           py310h06a4308_0
     jpeg                      9e                   h0b41bf4_3    conda-forge
     kiwisolver                1.4.4           py310hbf28c38_1    conda-forge
     krb5                      1.20.1               h143b758_1
     lame                      3.100             h166bdaf_1003    conda-forge
     lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
     lcms2                     2.15                 hfd0df8a_0    conda-forge
     ld_impl_linux-64          2.38                 h1181459_1
     lerc                      3.0                  h295c915_0
     libcublas                 12.1.0.26                     0    nvidia
     libcufft                  11.0.2.4                      0    nvidia
     libcufile                 1.7.0.149                     0    nvidia
     libcurand                 10.3.3.53                     0    nvidia
     libcurl                   8.1.1                h251f7ec_1
     libcusolver               11.4.4.55                     0    nvidia
     libcusparse               12.0.2.55                     0    nvidia
     libdeflate                1.17                 h0b41bf4_0    conda-forge
     libedit                   3.1.20221030         h5eee18b_0
     libev                     4.33                 h7f8727e_1
     libffi                    3.4.4                h6a678d5_0
     libflac                   1.4.3                h59595ed_0    conda-forge
     libgcc-ng                 13.1.0               he5830b7_0    conda-forge
     libgfortran-ng            11.2.0               h00389a5_1
     libgfortran5              11.2.0               h1234567_1
     libhiredis                1.0.2                h2cc385e_0    conda-forge
     libllvm14                 14.0.6               hdb19cb5_3
     libnghttp2                1.52.0               h2d74bed_1
     libnpp                    12.0.2.50                     0    nvidia
     libnvjitlink              12.1.105                      0    nvidia
     libnvjpeg                 12.1.1.14                     0    nvidia
     libogg                    1.3.4                h7f98852_1    conda-forge
     libopus                   1.3.1                h7f98852_1    conda-forge
     libpng                    1.6.39               h5eee18b_0
     libprotobuf               3.20.3               he621ea3_0
     librosa                   0.10.0             pyhd8ed1ab_2    conda-forge
     libsndfile                1.2.0                hb75c966_0    conda-forge
     libssh2                   1.10.0               hdbd6064_2
     libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
     libtiff                   4.5.0                h6a678d5_2
     libuuid                   1.41.5               h5eee18b_0
     libuv                     1.44.2               h5eee18b_0
     libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
     libvpx                    1.7.0                h439df22_0
     libwebp                   1.2.4                h1daa5a0_1    conda-forge
     libwebp-base              1.2.4                h5eee18b_1
     llvm-openmp               14.0.6               h9e868ea_0
     llvmlite                  0.40.0          py310he621ea3_0
     lz4-c                     1.9.4                h6a678d5_0
     magma-cuda116             2.6.1                         1    pytorch
     markupsafe                2.1.1           py310h7f8727e_0
     matplotlib-base           3.4.3           py310h23f4a51_2    conda-forge
     mkl                       2023.1.0         h6d00ec8_46342
     mkl-include               2023.1.0         h06a4308_46342
     mkl-service               2.4.0           py310h5eee18b_1
     mkl_fft                   1.3.6           py310h1128e8f_1
     mkl_random                1.2.2           py310h1128e8f_1
     mpc                       1.1.0                h10f8cd9_1
     mpfr                      4.0.2                hb69a4c5_1
     mpg123                    1.31.3               hcb278e6_0    conda-forge
     mpmath                    1.2.1                    pypi_0    pypi
     msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
     ncurses                   6.4                  h6a678d5_0
     nettle                    3.6                  he412f7d_0    conda-forge
     networkx                  2.8.4           py310h06a4308_1
     ninja                     1.10.2               h06a4308_5
     ninja-base                1.10.2               hd09550d_5
     numba                     0.57.1          py310h0f6aa51_0    conda-forge
     numpy                     1.24.3          py310h5f9d8c6_1
     numpy-base                1.24.3          py310hb5e798b_1
     openh264                  2.1.1                h4ff587b_0
     openssl                   3.0.9                h7f8727e_0
     packaging                 23.0            py310h06a4308_0
     pillow                    9.4.0           py310h6a678d5_0
     pip                       23.1.2          py310h06a4308_0
     pooch                     1.4.0              pyhd3eb1b0_0
     protobuf                  3.20.3          py310h6a678d5_0
     pycparser                 2.21               pyhd3eb1b0_0
     pyopenssl                 23.0.0          py310h06a4308_0
     pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
     pysocks                   1.7.1           py310h06a4308_0
     pysoundfile               0.12.1             pyhd8ed1ab_0    conda-forge
     python                    3.10.11              h955ad1f_3
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python_abi                3.10                    2_cp310    conda-forge
     pytorch                   2.1.0.dev20230703 py3.10_cuda12.1_cudnn8.9.2_0    pytorch-nightly
     pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
     pytorch-mutex             1.0                        cuda    pytorch-nightly
     pyyaml                    6.0             py310h5eee18b_1
     readline                  8.2                  h5eee18b_0
     requests                  2.29.0          py310h06a4308_0
     rhash                     1.4.3                hdbd6064_0
     scikit-learn              1.2.2           py310h6a678d5_1
     scipy                     1.10.1          py310h5f9d8c6_1
     setuptools                67.8.0          py310h06a4308_0
     six                       1.16.0             pyhd3eb1b0_1
     soxr                      0.1.3                h0b41bf4_3    conda-forge
     soxr-python               0.3.5           py310h278f3c1_0    conda-forge
     sqlite                    3.41.2               h5eee18b_0
     sympy                     1.11.1          py310h06a4308_0
     tbb                       2021.8.0             hdb19cb5_0
     threadpoolctl             2.2.0              pyh0d69192_0
     tk                        8.6.12               h1ccaba5_0
     torchtriton               2.1.0+440fd1bf20           py310    pytorch-nightly
     torchvision               0.16.0a0+43030cb          pypi_0    pypi
     tornado                   6.3.2           py310h2372a71_0    conda-forge
     typing_extensions         4.6.3           py310h06a4308_0
     tzdata                    2023c                h04d1e81_0
     urllib3                   1.26.16         py310h06a4308_0
     wheel                     0.38.4          py310h06a4308_0
     x264                      1!157.20191217       h7b6447c_0
     xz                        5.4.2                h5eee18b_0
     yaml                      0.2.5                h7b6447c_0
     zlib                      1.2.13               h5eee18b_0
     zstd                      1.5.5                hc292b87_0

**Comment by mkhadatare** [comment]
Hello @optyang, Thank you for reporting this issue.
Can you sync the folder from this link https://github.com/CVCUDA/CV-CUDA/tree/v0.3.0-beta/3rdparty/cuOSD 

We will fix the issue soon.

**Comment by complexfilter** [comment]
I have seen the same error. Has this issue been fixed? @mkhadatare .

**Comment by dlesage-nvidia** [comment]
Hi, thank you for your interest in CV-CUDA and your patience!
We expect that this issue has been resolved in most recent releases. 

We encourage you to look into https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.5.0-beta.
Thank you!
