### ISSUE TITLE
where is the file 'nvcv_python-0.3.1-cp38-cp38-linux_x86_64.whl'?

### ISSUE THREAD

**Issue by zhangsanfeng86** [CVCUDA/CV-CUDA#94]
**What is your question?**
where is the file 'nvcv_python-0.3.1-cp38-cp38-linux_x86_64.whl'?

**Comment by mkhadatare** [comment]
Hi @zhangsanfeng86 
Can you check this link https://github.com/CVCUDA/CV-CUDA/releases/download/v0.3.1-beta/nvcv_python-0.3.1_beta-cp38-cp38-linux_x86_64.whl

**Comment by complexfilter** [comment]
@mkhadatare why not put a link in the readme.md file?
